# Generated by Django 6.0.5 on 2026-05-20 12:48

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='main_singer_name_9b9174_idx'), models.Index(fields=['country'], name='main_singer_country_a32546_idx')],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Album muqovasi', null=True, upload_to='albums/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singer', models.ForeignKey(help_text="Qo'shiqchi", on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='main.singer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('other', 'Other')], db_index=True, max_length=100)),
                ('duration', models.DurationField(help_text="Qo'shiqning davomiyligi")),
                ('file', models.FileField(blank=True, help_text='Audio fayli', null=True, upload_to='songs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'flac', 'aac'], message='Ruxsat: MP3, WAV, FLAC, AAC')])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(help_text='Albom', on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='main.album')),
            ],
            options={
                'ordering': ['album', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['singer', '-created_at'], name='main_album_singer__5fde12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('name', 'singer')},
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['album', 'genre'], name='main_song_album_i_e59c51_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre', '-created_at'], name='main_song_genre_1bbd3d_idx'),
        ),
    ]
