# Generated by Django 6.0.5 on 2026-09-08 10:55

import django.core.validators
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_follow_genre_like_playlist_playlistsong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, help_text='Album muqovasi (max 5 MB)', null=True, upload_to='albums/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Ruxsat: JPG, JPEG, PNG, WEBP'), main.validators.MaxFileSizeValidator(max_mb=5)]),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, help_text='Audio fayli (max 20 MB)', null=True, upload_to='songs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'flac', 'aac'], message='Ruxsat: MP3, WAV, FLAC, AAC'), main.validators.MaxFileSizeValidator(max_mb=20)]),
        ),
    ]
